name: ci

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-22.04
    steps:
      -
        name: Set up Docker
        uses: docker/setup-docker-action@v4
      - name: checkout
        uses: actions/checkout@v4  
      - name: build image
        run: docker build ./ -t cuongdv20/fat12:latest
      - name: push image to docker hub
        run: docker push cuongdv20/fat12:latest
      